name: ibuclubs_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_bloc: ^9.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  equatable: ^2.0.7
  built_value: ^8.9.3
  built_collection: ^5.1.1
  auto_route: ^9.2.0
  chopper: ^8.1.0
  flutter_secure_storage: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.17
  global_configuration: ^2.0.0
  salomon_bottom_bar: ^3.3.2
  flutter_hooks: ^0.21.2
  rename_app: ^1.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.15
  auto_route_generator: ^9.0.0
  chopper_generator: ^8.1.0
  built_value_generator: ^8.9.3
  injectable_generator: ^2.6.0
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ibuclubs_logo.png"
  remove_alpha_ios: true

flutter_app_name:
  name: "IBU Clubs"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - config/

